[tool.poetry]
name = "vss365today-admin"
version = "0.1.0"
description = "Administration control panel for #vss365 today"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^1.1.4"
Flask-WTF = "^1.0.1"
gunicorn = "^20.1.0"
requests = "^2.28.1"
WTForms-Components = "^0.10.5"
sys-vars = {url = "https://github.com/le717/sys-vars/releases/download/v3.0.0/sys_vars-3.0.0-py3-none-any.whl"}
flask-google-fonts = {url = "https://github.com/le717/flask-google-fonts/releases/download/v1.0.0/flask_google_fonts-1.0.0-py3-none-any.whl"}
webargs = "^8.2.0"
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
black = "^21.12b0"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
